name: "Push"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: "read"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref != 'refs/heads/main' }}"

jobs:
  PushWranglerBuild:
    uses: ".github/workflows/push-wrangler-build.yaml"

  PushTest:
    uses: ".github/workflows/push-test.yaml"
