name: "Push"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: "read"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref != 'refs/heads/main' }}"

jobs:
  PushPrettier:
    uses: "./.github/workflows/prettier.yaml"
    permissions:
      contents: "read"

  PushTest:
    uses: "./.github/workflows/push-test.yaml"
    permissions:
      contents: "read"

  PushWranglerBuild:
    uses: "./.github/workflows/push-wrangler-build.yaml"
    permissions:
      contents: "read"
