name: "Test"

on:
  workflow_call:

permissions:
  contents: "read"

jobs:
  Test:
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Node"
        uses: "actions/setup-node@v4"
        with:
          node-version: "22"
          cache: 'npm'

      - name: "Install Dependencies"
        run: "npm ci"

      - name: "Build"
        run: "npx wrangler build --env=production"
